n1 = float(input("Fale um número: "))
n2 = float(input("Fale outro número: "))
s = n1 + n2
t = n1 - n2
m = n1 * n2
d = n1 / n2
p = n1 ** n2
print('A soma vale {}' .format(s), end=" ")
print('A subtração vale {} ' .format(t), end=' ')
print('A multiplicação vale {} ' .format(m), end=' ')
print('A divisão vale {} ' .format(d), end=' ')
print('A potenciação entre os dois fica {}' .format(p), end=' ')